// Code generated by github.com/dashotv/golem. DO NOT EDIT.
import { Response, ZapierRequest, imlfwClient } from '.';

export interface HooksZapierRequest {
  payload: ZapierRequest;
}

export const HooksZapier = async (params: HooksZapierRequest) => {
  const response = await imlfwClient.post(`/hooks/zapier?`, params.payload);

  if (!response.data) {
    throw new Error('response empty?');
  }

  if (response.data.error) {
    if (response.data.message) {
      throw new Error(response.data.message);
    }
    throw new Error('unknown error');
  }

  return response.data as Response;
};
