// Code generated by github.com/dashotv/golem. DO NOT EDIT.

export interface Email {
  id?: string;
  created_at?: string;
  updated_at?: string;

  thread_id?: string;
  subject?: string;
  body?: string;
  body_html?: string;
  date?: string;
  from_name?: string;
  from_email?: string;
  reply_to?: string;
  reply_name?: string;
}

export interface ZapierRequest {
  payload?: Email;
}
